services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: anira_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
            - "9000:9000"
        networks:
            - laravel

    webserver:
        image: nginx:alpine
        container_name: anira_nginx
        restart: unless-stopped
        ports:
            - "8080:80"
        volumes:
            - .:/var/www
            - ./nginx/conf.d:/etc/nginx/conf.d
        networks:
            - laravel
        depends_on:
            - app

    db:
        image: mysql:8.0
        container_name: anira_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: anira
            MYSQL_USER: anira
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
