networks:
    anira-network:
volumes:
    anira-data:
services:
    nginx:
        image: nginx:1.22.0-alpine
        container_name: 'anira-nginx'
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - .docker/nginx:/etc/nginx/conf.d
        networks:
            anira-network:
    app:
        container_name: 'anira-app'
        build:
            context: .docker/php
            dockerfile: dockerfile
        volumes:
            - ./:/var/www
            - .docker/php/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            anira-network:
    mysql:
        image: mysql:8.0.39
        container_name: 'anira-mysql'
        platform: linux/x86_64
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: anira_local
            MYSQL_USER: anira
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        volumes:
            - ./.mysql:/var/lib/mysql
        networks:
            anira-network:
